version: '3.4'

services:
  
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- "DatabaseSettings:ConnectionString=mongodb://localhost:27017"
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8080:80"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - discount.grpc
    ports:
      - "8081:80"
