version: '3.4'

services:
  
  catalog.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "50052:80"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "GrpcSettings:DiscountURL=http://discount.grpc:50051"
      - "GrpcCatalogSettings:CatalogURL=http://catalog.grpc:50052"
    depends_on:
      - discount.grpc
      - catalog.grpc
    ports:
      - "8081:80"
