version: '3.4'


services:
  catalogdb:
    image: mongo:latest
    #restart: always
    ports:
         - "27017:27017"
    container_name: catalogdb
    networks:
      - dev

  mongo_seed:
    image: catalogdb
    container_name: mongo-seed
    build: ./Catalog.GRPC/mongo-seed
    links:
      - catalogdb
    networks:
      - dev

  catalog.grpc:
    image: ${DOCKER_REGISTRY-}cataloggrpc
    container_name: catalog.grpc
    build:
      context: .
      dockerfile: Catalog.GRPC/Dockerfile
    networks:
      - dev

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    container_name: basket.api
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
    networks:
      - dev

  discount.grpc:
    image: hashorg/hash-mock-discount-service
    ports:
         - "50051:50051"
    container_name: discount.grpc
    networks:
      - dev

networks:
   dev:
     name: dev